### ISSUE TITLE
Submitting to Listary repository?

### ISSUE THREAD

**Issue by Chaoses-Ib** [wany-oh/Listary.FileAppPlugin.Explzh#1]
Hi, I'm a developer at Listary. I'm wondering if this plugin is production ready? If so, can we add it to Listary at the next release?

**Comment by wany-oh** [comment]
Thank you for your comment. There is no problem. If you could add this plugin to the next release, that would be great.

**Comment by Chaoses-Ib** [comment]
Listary [v6.3.0.51](https://discussion.listary.com/t/6-3-0-beta-is-live-new-file-search-window-updated-file-search-engine-new-user-documentation/8553?u=chaoses-ib) is now released.
